version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CALENDAR_API_URL=https://admin.xpectrum-ai.com/calendar-api
      - NEXT_PUBLIC_API_URL=https://admin.xpectrum-ai.com/api
      - NEXT_PUBLIC_PROPELAUTH_URL=https://auth.admin.xpectrum-ai.com
      - NEXT_PUBLIC_AUTH_URL=https://auth.admin.xpectrum-ai.com
      - PROPELAUTH_URL=${PROPELAUTH_URL}
      - PROPELAUTH_API_KEY=${PROPELAUTH_API_KEY}
      - SUPER_ADMIN_ORG_ID=${SUPER_ADMIN_ORG_ID}
    depends_on:
      - backend
      - calendar-backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "8085:8085"
    env_file:
      - ./backend/env.production
    environment:
      - NODE_ENV=production
      - PORT=8085
    restart: unless-stopped

  calendar-backend:
    build:
      context: ./calendar-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # Google OAuth Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=https://admin.xpectrum-ai.com/calendar-api/oauth2callback
      - CALENDAR_REDIRECT_URI=https://admin.xpectrum-ai.com/calendar-api/calendar/oauth2callback
      - FRONTEND_URL=https://admin.xpectrum-ai.com
      - SECRET_KEY=${SECRET_KEY}
      
      # MongoDB Configuration
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      
      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8001
      - DEBUG_MODE=false
      
      # API Configuration
      - API_VERSION=v1
      - API_PREFIX=/api/v1
      
      # Google OAuth URLs
      - GOOGLE_AUTH_URL=${GOOGLE_AUTH_URL}
      - PROPEL_TOKEN_URL=${PROPEL_TOKEN_URL}
      - GOOGLE_TOKEN_URL=${GOOGLE_TOKEN_URL}
      - PROPEL_USER_INFO_URL=${PROPEL_USER_INFO_URL}
      - PROPEL_GOOGLE_URL=${PROPEL_GOOGLE_URL}
      - GOOGLE_CALENDAR_API_URL=${GOOGLE_CALENDAR_API_URL}
      
      # OAuth Scopes
      - BASIC_SCOPES=${BASIC_SCOPES}
      - CALENDAR_SCOPES=${CALENDAR_SCOPES}
      
      # Calendar Configuration
      - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE:-America/New_York}
      - MAX_CALENDAR_EVENTS=${MAX_CALENDAR_EVENTS:-10}
      
      # CORS Configuration
      - CORS_ORIGINS=https://admin.xpectrum-ai.com,https://auth.admin.xpectrum-ai.com
      
      # PropelAuth Configuration
      - PROPELAUTH_URL=${PROPELAUTH_URL}
      - PROPELAUTH_API_KEY=${PROPELAUTH_API_KEY}
    restart: unless-stopped
    depends_on:
      - backend 