version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://admin-dev.xpectrum-ai.com/api
      - NEXT_PUBLIC_PROPELAUTH_URL=https://auth.admin-dev.xpectrum-ai.com
      - NEXT_PUBLIC_AUTH_URL=https://auth.admin-dev.xpectrum-ai.com
      - PROPELAUTH_URL=${PROPELAUTH_URL}
      - PROPELAUTH_API_KEY=${PROPELAUTH_API_KEY}
      - SUPER_ADMIN_ORG_ID=${SUPER_ADMIN_ORG_ID}
      - NEXT_PUBLIC_SUPER_ADMIN_ORG_ID=${SUPER_ADMIN_ORG_ID}
    restart: unless-stopped 