version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_LIVE_API_URL=${NEXT_PUBLIC_LIVE_API_URL}
        - NEXT_PUBLIC_LIVE_API_KEY=${NEXT_PUBLIC_LIVE_API_KEY}
        - NEXT_PUBLIC_PROPELAUTH_URL=${NEXT_PUBLIC_PROPELAUTH_URL}
        - NEXT_PUBLIC_PROPELAUTH_API_KEY=${NEXT_PUBLIC_PROPELAUTH_API_KEY}
        - NEXT_PUBLIC_SUPER_ADMIN_ORG_ID=${NEXT_PUBLIC_SUPER_ADMIN_ORG_ID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_LIVE_API_URL=${NEXT_PUBLIC_LIVE_API_URL}
      - NEXT_PUBLIC_LIVE_API_KEY=${NEXT_PUBLIC_LIVE_API_KEY}
      - NEXT_PUBLIC_PROPELAUTH_URL=${NEXT_PUBLIC_PROPELAUTH_URL}
      - NEXT_PUBLIC_PROPELAUTH_API_KEY=${NEXT_PUBLIC_PROPELAUTH_API_KEY}
      - NEXT_PUBLIC_SUPER_ADMIN_ORG_ID=${NEXT_PUBLIC_SUPER_ADMIN_ORG_ID}
    restart: unless-stopped 