export { default as AgentsTab } from './AgentsTab';
export { default as PhoneNumbersTab } from './PhoneNumbersTab';
export { default as SMSTab } from './SMSTab';
export { default as WhatsAppTab } from './WhatsAppTab';
export { default as GmailTab } from './GmailTab';
export { default as OverviewTab } from './OverviewTab';
export { default as Navbar } from './Navbar';
export { default as OrgSetup } from './OrgSetup';
export { default as WidgetConfig } from './config/WidgetConfig';
