export const SPECIALIZATIONS = [
  { "id": "allergy-immunology", "name": "Allergy & Immunology" },
  { "id": "anesthesiology", "name": "Anesthesiology" },
  { "id": "cardiology", "name": "Cardiology" },
  { "id": "dermatology", "name": "Dermatology" },
  { "id": "emergency-medicine", "name": "Emergency Medicine" },
  { "id": "endocrinology", "name": "Endocrinology" },
  { "id": "family-medicine", "name": "Family Medicine" },
  { "id": "gastroenterology", "name": "Gastroenterology" },
  { "id": "geriatrics", "name": "Geriatrics" },
  { "id": "hematology", "name": "Hematology" },
  { "id": "infectious-disease", "name": "Infectious Disease" },
  { "id": "internal-medicine", "name": "Internal Medicine" },
  { "id": "nephrology", "name": "Nephrology" },
  { "id": "neurology", "name": "Neurology" },
  { "id": "neurosurgery", "name": "Neurosurgery" },
  { "id": "obstetrics-gynecology", "name": "Obstetrics & Gynecology" },
  { "id": "oncology", "name": "Oncology" },
  { "id": "ophthalmology", "name": "Ophthalmology" },
  { "id": "orthopedic-surgery", "name": "Orthopedic Surgery" },
  { "id": "otolaryngology", "name": "Otolaryngology (ENT)" },
  { "id": "pathology", "name": "Pathology" },
  { "id": "pediatrics", "name": "Pediatrics" },
  { "id": "physical-medicine-rehabilitation", "name": "Physical Medicine & Rehabilitation" },
  { "id": "plastic-surgery", "name": "Plastic Surgery" },
  { "id": "psychiatry", "name": "Psychiatry" },
  { "id": "pulmonology", "name": "Pulmonology" },
  { "id": "radiology", "name": "Radiology" },
  { "id": "rheumatology", "name": "Rheumatology" },
  { "id": "sleep-medicine", "name": "Sleep Medicine" },
  { "id": "sports-medicine", "name": "Sports Medicine" },
  { "id": "surgery", "name": "Surgery" },
  { "id": "urology", "name": "Urology" },
  { "id": "vascular-surgery", "name": "Vascular Surgery" }
];
