name: Security

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run OWASP Dependency Check for Frontend
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Admin Panel Frontend'
        path: './frontend'
        format: 'HTML'
        out: 'reports/frontend'

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/
        retention-days: 30

  container-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner on Dockerfiles
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Log Trivy scan results
      run: |
        echo "Trivy scan completed"
        echo "Check the logs above for any vulnerabilities"

  secrets-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: HEAD~1
        head: HEAD

  npm-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Audit frontend dependencies
      run: |
        cd frontend
        npm audit --audit-level=moderate || echo "Audit completed with warnings"

  python-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install safety
      run: pip install safety

    - name: Check Python dependencies
      run: |
        cd python-cdk-v2
        safety check --output json --save safety-report.json || echo "Safety check completed with warnings"

  notify-security-issues:
    runs-on: ubuntu-latest
    needs: [dependency-check, container-scan, secrets-scan, npm-audit, python-security]
    if: always()
    
    steps:
    - name: Check for security issues
      id: check-issues
      run: |
        # Check if any of the security jobs failed
        if [[ "${{ needs.dependency-check.result }}" == "failure" ]] || \
           [[ "${{ needs.container-scan.result }}" == "failure" ]] || \
           [[ "${{ needs.secrets-scan.result }}" == "failure" ]] || \
           [[ "${{ needs.npm-audit.result }}" == "failure" ]] || \
           [[ "${{ needs.python-security.result }}" == "failure" ]]; then
          echo "has-issues=true" >> $GITHUB_OUTPUT
        else
          echo "has-issues=false" >> $GITHUB_OUTPUT
        fi

    - name: Log security status
      if: steps.check-issues.outputs.has-issues == 'true'
      run: |
        echo "Security issues detected in the workflow"
        echo "Please review the security scan results"
 